# Generated by Django 5.0.6 on 2024-06-25 22:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cfaf615-cc6c-405d-abcb-0f4fe8ca0993'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cfaf615-cc6c-405d-abcb-0f4fe8ca0993'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cfaf615-cc6c-405d-abcb-0f4fe8ca0993'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2cfaf615-cc6c-405d-abcb-0f4fe8ca0993'), editable=False, primary_key=True, serialize=False),
        ),
    ]
